### ISSUE TITLE
ArgumentOutOfRangeException and reset of analog-specific setting with CTCSS admit criteria

### ISSUE THREAD

**Issue by byannoni** [rogerclarkmelbourne/radioddity_gd-77_cps2.0.5#41]
If an analog channel is set up with CTCSS/DCS admit criteria, the analog group settings are reset after selecting a digital channel and then returning to the analog channel. It appears that the "Admit Criteria" selection is the triggering factor -- a channel can have both an Rx and a Tx tone without this issue if the admit criteria is none.

This issue is not present when selecting and returning from another analog channel or when closing and reopening the same channel. 

This issue occurs even if a different analog channel is selected between the digital channel and the channel in question. This issue occurs with both CTCSS and DCS tones and in both 2.0.5 and 3.0.6.

I was able to reproduce this issue with a new blank code plug.

**Steps to reproduce:**

1. Create a digital channel
2. Create a analog channel
3. Open the analog channel
4. Select an "Rx Tone"
5. Select a "Tx Tone"
6. Select "CTCSS/DCS" for "Admit Criteria"
7. Open the digital channel
8. Open the analog channel
9. Observe the exception
10. Observe that the "Analog" group controls have been reset

**Exception text:**

```
System.ArgumentOutOfRangeException: InvalidArgument=Value of '2' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at DMR.ChannelForm.DispData() in d:\projects\rogerclark\DMR\radioddity_gd-77_cps2.0.5\DMR\ChannelForm.cs:line 2478
   at DMR.MainForm.method_7(TreeNode treeNode_0, Boolean bool_0) in d:\projects\rogerclark\DMR\radioddity_gd-77_cps2.0.5\DMR\MainForm.cs:line 1301
   at DMR.MainForm.tvwMain_DoubleClick(Object sender, EventArgs e) in d:\projects\rogerclark\DMR\radioddity_gd-77_cps2.0.5\DMR\MainForm.cs:line 1793
   at System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by rogerclarkmelbourne** [comment]
Thanks

Do you know if the official CPS does this ?

I made some changes to the channel form to address the Dual Capacity Direct   bug, so if its in my version not the official one, I suspect thats perhaps whats causing the problem

**Comment by byannoni** [comment]
Thanks for the quick response.

I was able to reproduce the issue with the same steps in the "v2.0.5" official CPS.

**Comment by rogerclarkmelbourne** [comment]
OK
Thanks

That means its not been caused by the changes I made

Are you using the latest installer from the development branch or the older version from the master branch

**Comment by byannoni** [comment]
I only have the development branch 3.0.6 version installed at the moment. The master branch 2.0.5 version is the "2.0.5" that I tested (which does have this issue).

**Comment by rogerclarkmelbourne** [comment]
OK

I don't think ChannelsForm.cs has changed recently.

I'll see if I can figure out whats causing the crash

**Comment by rogerclarkmelbourne** [comment]
The problem seems to be that the Admit criteria has the CTCSS/DSS option removed if the code thinks the TXTone is set to None.

However the code is checking the value of the TxTone combobox (dropdown menu), and it can't do that until the page has finished being displayed

I've just tested a fix where I get the value of the Tx Tone correctly form the codeplug data, and that fixes it

However, it seems pointless doing removing the CTCSS/DSS option from the menu at all, because there isn't an option of "None" for the TxTone in the current setup

AFIK the Tones are loaded from an external file called Tone.txt (but I'm not sure why the CPS does this)
It seems odd that the only dropdown where the options are loaded from a file are these tx tones

I will need to check with a few other people to find the best fix, but I may commit the fix that I have at the moment as it does resolve the problem

**Comment by byannoni** [comment]
Awesome, that solved it. Thanks!

**Comment by rogerclarkmelbourne** [comment]
Looking again at this code, I may make another change so that the code that does this can be called, as it seems to also code to add the CTCSS/DSC menu option (if its is not present).

And it has been pointed out to me by Colin G4EML that the whole logic of this is flawed as it doesnt also check the RxTone setting
